Projet Final/Controllers/FurnitureController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Projet_Final.Data.Services;
using Projet_Final.Models;

namespace Projet_Final.Controllers
{
	public class FurnitureController : Controller
	{
		private readonly IFurnitureService _service;
		private readonly IFurnitureTypeService _serviceType;

		public FurnitureController(IFurnitureService service, IFurnitureTypeService serviceType)
		{
			_service = service;
			_serviceType = serviceType;
		}

		// GET: Furniture/
		public async Task<IActionResult> Index()
		{
			// Récupérer la liste des meubles
			IEnumerable<Furniture> furnitures = await _service.GetAllAsync();
			return View(furnitures);
		}

		// GET: Furniture/Details/1
		public async Task<IActionResult> Details(int id)
		{
			var furniture = await _service.GetByIdAsync(id);
			if (furniture == null) return View("NotFound");
			return View(furniture);
		}

		// GET: Furniture/Create
		public async Task<IActionResult> Create()
		{
			IEnumerable<FurnitureType> types = await _serviceType.GetAllAsync();
			ViewBag.TypeFurnitureId = new SelectList(types, "Id", "Name");
			return View();
		}

		// POST: Furniture/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Description,UrlPicture,Price,Comments,TypeFurnitureId")] Furniture furniture)
		{
			if (ModelState.IsValid)
			{
				if (!await _service.AddNewAsync(furniture))
				{
					ModelState.AddModelError("Name", "Le meuble existe déjà");
					return View(furniture);
				}
				return RedirectToAction(nameof(Index));
			}
			var types = await _serviceType.GetAllAsync();
			ViewBag.TypeFurnitureId = new SelectList(types, "Id", "Name");
			return View(furniture);
		}

		// GET: Furniture/Edit/1
		public async Task<IActionResult> Edit(int id)
		{
			var furniture = await _service.GetByIdAsync(id);
			if (furniture == null) return View("NotFound");
			var types = await _serviceType.GetAllAsync();
			ViewBag.TypeFurnitureId = new SelectList(types, "Id", "Name");
			return View(furniture);
		}

		// POST: Furniture/Edit/1
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,UrlPicture,Price,Comments,TypeFurnitureId")] Furniture furniture)
		{
			if (!ModelState.IsValid)
			{
				var furnitureTypes = await _serviceType.GetAllAsync();
				ViewBag.TypeFurnitureId = new SelectList(furnitureTypes, "Id", "Name", furniture.TypeFurnitureId);
				return View(furniture);
			}
			await _service.UpdateAsync(id, furniture);
			var types = await _serviceType.GetAllAsync();
			ViewBag.TypeFurnitureId = new SelectList(types, "Id", "Name");
			return RedirectToAction(nameof(Index));
		}

		// GET: Furniture/Delete/1
		public async Task<IActionResult> Delete(int id)
		{
			var furniture = await _service.GetByIdAsync(id);
			if (furniture == null) return View("NotFound");
			return View(furniture);
		}

		// POST: Furniture/Delete/1
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var furniture = await _service.GetByIdAsync(id);
			if (furniture == null) return View("NotFound");
			await _service.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}
	}
}

Projet Final/Controllers/FurnitureTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Projet_Final.Data.Services;
using Projet_Final.Models;

namespace Projet_Final.Controllers
{
	public class FurnitureTypeController : Controller
	{
		private readonly IFurnitureTypeService _service;

		public FurnitureTypeController(IFurnitureTypeService service)
		{
			_service = service;
		}

		// GET: FurnitureType/
		public async Task<IActionResult> Index()
		{
			// Récupérer la liste des types de meubles
			IEnumerable<FurnitureType> furnitureTypes = await _service.GetAllAsync();
			return View(furnitureTypes);
		}

		// GET: FurnitureType/Details/1
		public async Task<IActionResult> Details(int id)
		{
			FurnitureType furnitureType = await _service.GetByIdAsync(id);
			return View(furnitureType);
		}

		// GET: FurnitureType/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: FurnitureType/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name")] FurnitureType furnitureType)
		{
			if (ModelState.IsValid)
			{
				if (!await _service.AddNewAsync(furnitureType))
				{
					ModelState.AddModelError("Name", "Le type de meuble existe déjà");
					return View(furnitureType);
				}
				return RedirectToAction(nameof(Index));
			}
			return View(furnitureType);
		}

		// GET: FurnitureType/Edit/1
		public async Task<IActionResult> Edit(int id)
		{
			var furnitureType = await _service.GetByIdAsync(id);
			if (furnitureType == null) return View("NotFound");
			return View(furnitureType);
		}

		// POST: FurnitureType/Edit/1
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] FurnitureType furnitureType)
		{
			if (!ModelState.IsValid)
			{
				return View(furnitureType);
			}
			await _service.UpdateAsync(id, furnitureType);
			return RedirectToAction(nameof(Index));
		}

		// GET: FurnitureType/Delete/1
		public async Task<IActionResult> Delete(int id)
		{
			var furnitureType = await _service.GetByIdAsync(id);
			if (furnitureType == null) return View("NotFound");
			return View(furnitureType);
		}

		// POST: FurnitureType/Delete/1
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var furnitureType = await _service.GetByIdAsync(id);
			if (furnitureType == null) return View("NotFound");
			await _service.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}
	}
}

Projet Final/Views/Shared/NotFound.cshtml
<div class="row text-center">
	<h1 class="text-danger">Ops! Désolé! Cet élément n'est pas encore disponible</h1>
	<hr />
	<a class="btn btn-secondary" asp-controller="Livre" asp-action="Index">Home Page</a>

</div>

Projet Final/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] | Larmoire Wood Furnitures</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Projet_Final.styles.css" asp-append-version="true" />
	<link rel="icon" type="image/x-icon" href="~/img/larmoire-logo.png">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 w-100">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
					<img src="~/img/header-logo.png" alt="Header Logo" style="height: 70px;" />
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Magasin</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Management
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" asp-controller="Furniture" asp-action="Index">Furnitures</a></li>
								<li><a class="dropdown-item" asp-controller="FurnitureType" asp-action="Index">Types de Furniture</a></li>
							</ul>
						</li>
					</ul>
					<form class="d-flex" asp-controller="Home" asp-action="Filter" role="search">
						<input name="searchString" class="form-control me-2" type="search" placeholder="Recherche" aria-label="Search">
						<button class="btn btn-outline-success" type="submit">Recherche</button>
					</form>
					<ul class="navbar-nav">
						@await Component.InvokeAsync("ShoppingCartSummary")
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container-fluid">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted bg-dark mt-4 py-2 w-100">
		<div class="container text-center text-white">
			Larmoire Wood Furnitures &copy; 2025 - Bellinazzi Ltda. - <a class="text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>